import colors from "tailwindcss/colors";
import tailwindTheme from "tailwindcss/defaultTheme";

import { Theme } from "../types";
import { hexWithAlpha } from "../utils/color";

const slateA = {
  100: hexWithAlpha(colors.slate["900"], 0.03),
  200: hexWithAlpha(colors.slate["900"], 0.06),
  300: hexWithAlpha(colors.slate["900"], 0.14),
  400: hexWithAlpha(colors.slate["900"], 0.31),
  500: hexWithAlpha(colors.slate["900"], 0.49),
};

export const defaultTheme: Theme = {
  light: {
    color: {
      text: {
        base: colors.slate["900"],
        subtle: colors.slate["700"],
        subtlest: colors.slate["600"],
        inverse: colors.white,
        disabled: slateA["400"],
        link: colors.blue["600"],
        linkHovered: colors.blue["600"],
        linkPressed: colors.blue["700"],
        primary: colors.blue["600"],
        success: colors.green["700"],
        info: colors.sky["700"],
        warning: colors.amber["700"],
        warningInverse: colors.stone["900"],
        danger: colors.red["700"],
        help: colors.violet["700"],
        selected: colors.blue["600"],
      },
      icon: {
        base: colors.slate["700"],
        subtle: colors.slate["600"],
        subtlest: colors.slate["500"],
        inverse: colors.white,
        disabled: slateA["400"],
        primary: colors.blue["600"],
        success: colors.green["500"],
        info: colors.sky["500"],
        warning: colors.amber["500"],
        warningInverse: colors.stone["900"],
        danger: colors.red["500"],
        help: colors.violet["500"],
        selected: colors.blue["600"],
      },
      border: {
        base: slateA["300"],
        input: slateA["300"],
        inverse: colors.white,
        disabled: slateA["200"],
        primary: colors.blue["600"],
        success: colors.green["500"],
        info: colors.sky["500"],
        warning: colors.amber["500"],
        danger: colors.red["500"],
        help: colors.violet["500"],
        focused: colors.blue["400"],
        selected: colors.blue["600"],
      },
      bg: {
        base: colors.white,
        surface: colors.white,
        surfaceHovered: colors.slate["100"],
        surfacePressed: colors.slate["200"],
        surfaceRaised: colors.white,
        surfaceRaisedHovered: colors.slate["100"],
        surfaceRaisedPressed: colors.slate["200"],
        surfaceOverlay: colors.white,
        surfaceOverlayHovered: colors.slate["100"],
        surfaceOverlayPressed: colors.slate["200"],
        surfaceSunken: colors.slate["100"],
        input: colors.white,
        inputHovered: colors.slate["50"],
        inputPressed: colors.white,
        disabled: slateA["100"],
        backdrop: slateA["500"],
        inverseSubtle: "#00000029",
        inverseSubtleHovered: "#0000003D",
        inverseSubtlePressed: "#00000052",
        neutralBold: colors.slate["700"],
        neutralBoldHovered: colors.slate["800"],
        neutralBoldPressed: colors.slate["900"],
        neutral: slateA["200"],
        neutralHovered: slateA["300"],
        neutralPressed: slateA["400"],
        neutralSubtle: colors.transparent,
        neutralSubtleHovered: slateA["200"],
        neutralSubtlePressed: slateA["300"],
        primaryBold: colors.blue["600"],
        primaryBoldHovered: colors.blue["700"],
        primaryBoldPressed: colors.blue["800"],
        primary: colors.blue["50"],
        primaryHovered: colors.blue["100"],
        primaryPressed: colors.blue["200"],
        successBold: colors.green["600"],
        successBoldHovered: colors.green["700"],
        successBoldPressed: colors.green["800"],
        success: colors.green["50"],
        successHovered: colors.green["100"],
        successPressed: colors.green["200"],
        infoBold: colors.sky["600"],
        infoBoldHovered: colors.sky["700"],
        infoBoldPressed: colors.sky["800"],
        info: colors.sky["50"],
        infoHovered: colors.sky["100"],
        infoPressed: colors.sky["200"],
        warningBold: colors.amber["300"],
        warningBoldHovered: colors.amber["400"],
        warningBoldPressed: colors.amber["500"],
        warning: colors.amber["50"],
        warningHovered: colors.amber["100"],
        warningPressed: colors.amber["200"],
        dangerBold: colors.red["600"],
        dangerBoldHovered: colors.red["700"],
        dangerBoldPressed: colors.red["800"],
        danger: colors.red["50"],
        dangerHovered: colors.red["100"],
        dangerPressed: colors.red["200"],
        helpBold: colors.violet["600"],
        helpBoldHovered: colors.violet["700"],
        helpBoldPressed: colors.violet["800"],
        help: colors.violet["50"],
        helpHovered: colors.violet["100"],
        helpPressed: colors.violet["200"],
        selectedBold: colors.blue["600"],
        selectedBoldHovered: colors.blue["700"],
        selectedBoldPressed: colors.blue["800"],
        selected: colors.blue["50"],
        selectedHovered: colors.blue["100"],
        selectedPressed: colors.blue["200"],
      },
    },
    shadow: {
      surfaceRaised: tailwindTheme.boxShadow.DEFAULT,
      surfaceOverlay: tailwindTheme.boxShadow.lg,
    },
  },
  dark: {
    color: {
      text: {
        base: "",
        subtle: "",
        subtlest: "",
        inverse: "",
        disabled: "",
        link: "",
        linkHovered: "",
        linkPressed: "",
        primary: "",
        success: "",
        info: "",
        warning: "",
        warningInverse: "",
        danger: "",
        help: "",
        selected: "",
      },
      icon: {
        base: "",
        subtle: "",
        subtlest: "",
        inverse: "",
        disabled: "",
        primary: "",
        success: "",
        info: "",
        warning: "",
        warningInverse: "",
        danger: "",
        help: "",
        selected: "",
      },
      border: {
        base: "",
        input: "",
        inverse: "",
        disabled: "",
        primary: "",
        success: "",
        info: "",
        warning: "",
        danger: "",
        help: "",
        focused: "",
        selected: "",
      },
      bg: {
        base: "",
        surface: "",
        surfaceHovered: "",
        surfacePressed: "",
        surfaceRaised: "",
        surfaceRaisedHovered: "",
        surfaceRaisedPressed: "",
        surfaceOverlay: "",
        surfaceOverlayHovered: "",
        surfaceOverlayPressed: "",
        surfaceSunken: "",
        input: "",
        inputHovered: "",
        inputPressed: "",
        disabled: "",
        backdrop: "",
        inverseSubtle: "",
        inverseSubtleHovered: "",
        inverseSubtlePressed: "",
        neutralBold: "",
        neutralBoldHovered: "",
        neutralBoldPressed: "",
        neutral: "",
        neutralHovered: "",
        neutralPressed: "",
        neutralSubtle: "",
        neutralSubtleHovered: "",
        neutralSubtlePressed: "",
        primaryBold: "",
        primaryBoldHovered: "",
        primaryBoldPressed: "",
        primary: "",
        primaryHovered: "",
        primaryPressed: "",
        successBold: "",
        successBoldHovered: "",
        successBoldPressed: "",
        success: "",
        successHovered: "",
        successPressed: "",
        infoBold: "",
        infoBoldHovered: "",
        infoBoldPressed: "",
        info: "",
        infoHovered: "",
        infoPressed: "",
        warningBold: "",
        warningBoldHovered: "",
        warningBoldPressed: "",
        warning: "",
        warningHovered: "",
        warningPressed: "",
        dangerBold: "",
        dangerBoldHovered: "",
        dangerBoldPressed: "",
        danger: "",
        dangerHovered: "",
        dangerPressed: "",
        helpBold: "",
        helpBoldHovered: "",
        helpBoldPressed: "",
        help: "",
        helpHovered: "",
        helpPressed: "",
        selectedBold: "",
        selectedBoldHovered: "",
        selectedBoldPressed: "",
        selected: "",
        selectedHovered: "",
        selectedPressed: "",
      },
    },
    shadow: {
      surfaceRaised:
        "0px 0px 0px rgba(0, 0, 0, 0),0px 1px 1px rgba(3, 4, 4, 0.5),0px 0px 1px rgba(3, 4, 4, 0.5)",
      surfaceOverlay:
        "0px 0px 0px rgba(188, 214, 240, 0.04),0px 8px 12px rgba(3, 4, 4, 0.36),0px 0px 1px rgba(3, 4, 4, 0.5)",
    },
  },
  common: {},
};
